[build]
target = "index.html"
dist = "dist"
public_url = "./"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx @tailwindcss/cli -i style/tailwind.css -o style/output.css --minify"]
